{
     "cancel-button-text": "Cancel",
     "cumulative-from-start-text": "Cumulative From Start",
     "end-date-error-text": "  - The End Date is invalid\n",
     "end-date-field": "End Date:",
     "end-date-larger-error-text": "  - The End Date cannot be greater than today's Date\n",
     "interval-count-field": "Interval Count:",
     "loop-playback-field": "Loop Playback:",
     "ok-button-text": "OK",
     "playback-speed-error-text": "  - The Playback Speed must be between {0} and {1} seconds\n",
     "playback-speed-field": "Playback Speed (seconds):",
     "settings-validation-error-text_close": "\nPlease try again.",
     "settings-validation-error-text_intro": "Some fields contain missing or invalid information:\n\n",
     "settings-validation-error-title": "Validation Error",
     "slider-dual-year-header-text": "Year Range: {0} to {1}",
     "slider-settings-popup-title": "Time Slider Settings",
     "slider-single-year-header-text": "Current Year: {0}",
     "start-date-error-text": "  - The Start Date is invalid\n",
     "start-date-field": "Start Date:",
     "start-date-larger-error-text": "  - The Start Date must be less than the End Date\n",
     "time-extent-text": "Time Extent",
     "time-instant-text": "Time Instant",
     "time-mode-field": "Time Mode:"
}